name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies from pyproject.toml
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Install pylint
      run: |
        pip install pylint
    - name: Run Pylint Analysis
      run: |
        pylint $(git ls-files '*.py') --disable=C0114,C0103,R0902,R0903 --max-line-length=120
